components/pages/common/TheNewsList.vue
components/pages/top/TheNewsList.vue
pages/index.vue
pages/news/_id.vue
pages/news/index.vue

* ニュース一覧ページの作成
* https://github.com/egg-system/corporate-site/issues/27
* ニュース詳細ページの作成
* https://github.com/egg-system/corporate-site/issues/29
* 新規ページ作成のため
* ニュースページの作成

ニュースページの作成

---

components/pages/common/TheColumnList.vue
components/pages/common/TheNewsList.vue
components/pages/top/TheColumnList.vue
components/pages/top/TheNewsList.vue
pages/column/_id.vue
pages/column/index.vue
pages/news/_id.vue

* コラムリスト、詳細ページの作成
* https://github.com/egg-system/corporate-site/issues/28
* https://github.com/egg-system/corporate-site/issues/30
* 新規作成
* 新規ページ作成

コラムリスト、詳細ページの作成

---

pages/privacy.vue

* プライバシーポリシーページの作成
* https://github.com/egg-system/corporate-site/issues/35
* 新規ページ作成
* プライバシーポリシーページの作成

プライバシーポリシーページの作成

---

assets/common.scss
components/pages/top/TheColumnList.vue
lib/cms.js
package-lock.json
package.json
pages/column/_id.vue

* コラムの詳細画面のレイアウトを調整
* 文字サイズ幅を調整

コラム画面の詳細画面

---

components/layouts/Header.vue

相対パス修正
* 課題の概要を記述します
* 何故やるのか目的を記述します
* 具体的な対応内容を記述します

お問い合わせページ遷移バグ修正

---

assets/main.scss

* 文字感覚が詰まっているのでsoup stockと同じに修正
* body全体にletter-spacingを指定

全文字の文字間隔とsoup stockに統一

---

assets/main.scss
components/pages/common/TheColumnList.vue
components/pages/common/TheLinkButton.vue
components/pages/top/TheAbout.vue
components/pages/top/TheContact.vue
components/pages/top/TheMember.vue
components/pages/top/TheService.vue
components/pages/top/TheSubHeader.vue
pages/index.vue

@eggsystem 
#100の修正です。
・全体的なレイアウト修正
・コラムとメンバーのリンク修正(コンポーネント化しました)
・サービスとお問い合わせのボタン修正
わたしたちについてのレイアウトもスープストックに寄せました。
写真の高さがもっと低いですが、こちらの写真だと画像がおかしくなります。
ご確認よろしくお願いします。

トップページ改修 #100

---

components/pages/common/TheColumnList.vue
pages/column/index.vue

コラム一覧レイアウト調整

---

components/pages/request/TheService.vue

* サービス画面のフォントサイズ変更
* サービス名の説明文の文字サイズを変更

サービス画面のフォントサイズ変更

---

components/pages/common/TheColumnList.vue

文字のはみ出し＆被り修正

---

pages/column/_id.vue

コラム詳細の「一覧を見る」を黒くする

---

pages/column/_id.vue

* blockquoteのデザインを変更
* 指定のものに変更

blockquoteデザイン変更

---

components/layouts/Footer.vue
components/pages/common/TheNewsList.vue
pages/index.vue

* ニュース画面へのリンクを追加
* トップ画面のコメントを外す
* フッターにリンクを追加

ニュース画面へのリンクを追加

---

components/pages/common/TheColumnList.vue
components/pages/common/TheNewsList.vue
pages/news/_id.vue
pages/news/index.vue

* 課題の概要を記述します
* 何故やるのか目的を記述します
* 具体的な対応内容を記述します

Newsの画像サイズ調整とトップと詳細のニュースのアイキャッチ画像非表示

---

nuxt.config.js
package-lock.json
package.json

GoogleAdsenseエラー修正

---

components/layouts/Footer.vue

- フッターに個別のサービスページへのリンクを追加
- 回遊率向上のため
- フッターに個別のサービスページへのリンクを追加

フッターに個別のサービスページへのリンクを追加

---

components/pages/service/TheServiceDetails.vue
components/pages/top/TheMainMessage.vue
nuxt.config.js
pages/index.vue
pages/service/index.vue
pages/service/it-control.vue

- SEO改善のため、キーワードを追加
- 「システム コンサルティング」のキーワードを増やす
-  内部統制に「ガバナンス」のキーワードを追加する
- SEO改善のため
- 各種キーワードの追加

h2やディスクリプションにキーワードを追加

---

assets/posts.scss
components/pages/common/TheColumnList.vue
components/pages/common/TheNewsList.vue
pages/cases/_id.vue
pages/column/_id.vue
pages/news/_id.vue

- デザイン調整および、SEO強化のため
- SEO改善
- UX向上
- 更新日を追加する
- タイトルと日付がかぶらないように修正

更新日の追加&日付とタイトルがかぶる件に対応

---

components/organisms/SimulatorForm.vue
pages/service/it-cost/index.vue

- ITコストシミュレーションにコスト削減の文言を追加する
- SEO対策のため
- メタタグにコスト削減の文言を追加する

ITコストシミュレーションにコスト削減の文言を追加する

---

components/atoms/conversions/DefaultConversionComponent.vue
components/layouts/ConversionZone.vue
components/layouts/Footer.vue
components/layouts/TheConversion.vue
layouts/default.vue
middleware/conversion-zone.js
store/conversion.js

- CVゾーンの追加
- 資料ダウンロードCVの向上のため
- 資料ダウンロードの導線を追加

feat : ダウンロードのCVゾーンを追加

---

nuxt.config.js

- ヒートマップによる解析タグの導入
- CVなどの向上施策を検討するため
- 離脱の原因などを測る
- HotJarというサービスを導入
- spaに対応しているため
- User HeatはSPAに対応していなさそうだったので、保留
- 下記からログイン可能
- https://insights.hotjar.com/sites/2178076/dashboard

ヒートマップ用の解析タグを埋め込む
